name: MyPortfolio
description: "an app to manage my portfolio and CV"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^1.5.1
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  google_fonts: ^6.1.0
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.4.0
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/