// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE6pqn951B4rm7R5gYiDRjF248Dy1Aaf0',
    appId: '1:1028786253478:web:6253e5ad3efb5e61554e67',
    messagingSenderId: '1028786253478',
    projectId: 'portfolio-43a74',
    authDomain: 'portfolio-43a74.firebaseapp.com',
    storageBucket: 'portfolio-43a74.appspot.com',
    measurementId: 'G-YCDV5MXFQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABXjjxtjv5v_YUgDoO_n9YFYipSS3VvwM',
    appId: '1:1028786253478:android:071f5117fe4b5421554e67',
    messagingSenderId: '1028786253478',
    projectId: 'portfolio-43a74',
    storageBucket: 'portfolio-43a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2zR2-QxhuhY6pZybW4abf9_j85aEFw9o',
    appId: '1:1028786253478:ios:186c2c5ee3e0b0a3554e67',
    messagingSenderId: '1028786253478',
    projectId: 'portfolio-43a74',
    storageBucket: 'portfolio-43a74.appspot.com',
    iosBundleId: 'com.imdvlpr.portfolio',
  );
}
